### ISSUE TITLE
Upgrade failed with bin file

### ISSUE THREAD

**Issue by zacra91** [convergeone/freeztp#62] opened 2020-02-24 17:30 UTC
Hi,

I have been trying to upgrade with my Cisco 2960S in my lab, When ZTP tried to upgrade with bin file IOS, it's doesn't work. 

Loading freeztp_ios_upgrade from 10.0.1.13 (via Vlan1): !
[OK - 34 bytes]

examining image...
%Tar checksum error in tftp://10.0.1.13/c2960s-universalk9-mz.152-2.E5.bin
%Error opening flash:update/info (No such file or directory)
ERROR: Image is not a valid IOS image archive.
Mar 30 01:32:46.401: AUTOINSTALL: Error (1) Image is not a valid IOS image archive or not existing
Mar 30 01:32:46.412: AUTOINSTALL: Obtain tftp server address (opt 150) 10.0.1.13

We can see that iOS has been uploaded.

 2020-02-24 19:12:27  |  10.0.1.14  |  c2960s-universalk9-mz.152-2.E5.bin  |  16940032  |  16940032   |   100.0   |  0 bps  |  False 

After this failed I tried to upgrade with a tar file and it's work really well.
Is there anything I forgot ? Could you help me ?

Thank you

Regards

**Comment by PackeTsar** [comment] 2020-02-24 17:33
See https://github.com/PackeTsar/freeztp/issues/42

**Comment by derek-shnosh** [comment] 2020-02-24 17:34
This is a duplicate of #42; 2960 requires .tar file for upgrade.

I found the .tar file upgrade process lengthy and cumbersome, so you may try out [ZTP-Watcher](https://github.com/derek-shnosh/ztp-watcher) to work around this issue.

**Closed as completed** 2020-02-24 17:33 UTC

**Comment by zacra91** [comment] 2020-02-24 17:42
Ok sorry I didn't see the closed ticket.

I'm going to see this ticket !

Thank you guys :)

**Comment by PackeTsar** [comment] 2020-02-24 17:47
No problem @zacra91

**Comment by zacra91** [comment] 2020-02-24 17:52
And your program is anwsome!!!

Thx
