### ISSUE TITLE
GUI login issues after installing V1.1.0 FreeZTP on a RaspberryPI

### ISSUE THREAD

**Issue by RichGu** [convergeone/freeztp#41] opened 2019-03-19 19:42 UTC
After installing the FreeZTP I’m getting an .xession-errors issue
/etc/X11/Xsession: 11: /etc/profile.d/zip-complete.sh: Syntax error: “(“ unexpected (expecting “}”)

**Comment by PackeTsar** [comment] 2019-05-23 17:49
Any indication on which line of the file this is referencing? Can you tweak with that completion script to see where BASH is getting pissed off and let me know?

**Comment by PackeTsar** [comment] 2019-05-24 20:58
I have received a second report of this happening. Going to install on Rasperian and see if I can reproduce.

**Comment by PackeTsar** [comment] 2019-05-24 21:30
I am tracking this bug in a central issue. Closing this issue.

**Comment by PackeTsar** [comment] 2020-04-11 22:04
Looks the root cause of this is that FreeZTP installs a BASH completion file into the `/etc/profile.d/` directory. This is typically OK with Linux installs not having a GUI component.

In the case of Rasperian with a GUI, Rasperian tries to run the scripts in the `/etc/profile.d/` directory with `sh` instead of `bash`. The completion script is bash-based and errors out when run by `sh` which causes a user to log into the GUI, the screen blanks out, and then returns to the login screen; failing to log in.

The bug fix should be:
- Delete the completion script in the `/etc/profile.d/` directory
- Install the script in the `/etc/bash_completion.d` directory

This should still run the script upon bash login, but not upon GUI login

**Comment by PackeTsar** [comment] 2020-04-11 22:06
This fix is being prepared and will be ready in the next release. Apologies for breaking your Raspberry Pi profile

**Closed as completed by PackeTsar** 2020-04-11 22:06 UTC
Labels: bug
